# Generated by Django 3.0.5 on 2020-08-19 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='a',
        ),
    ]
