# Generated by Django 3.0.5 on 2020-08-19 13:24

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0002_remove_link_a'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='ip_views',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), size=None), default=list, size=None),
        ),
        migrations.AddField(
            model_name='link',
            name='unique_views_count_browsers',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), default=list, size=None),
        ),
        migrations.AddField(
            model_name='link',
            name='unique_views_count_devices',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), default=list, size=None),
        ),
    ]
