# Generated by Django 3.0.5 on 2020-08-19 13:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0003_auto_20200819_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='ip_views',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), default=list, size=None), default=list, size=None),
        ),
    ]
